### ISSUE TITLE
Add system error build status

### ISSUE THREAD

**Issue by shankj3** [level11consulting/orbitalci#122]
a bug was found that took down the server over the course of an `ocelot build`. the bug was fixed, but in the aftermath the postgres database has a bunch of 'builds' that are all under `queued`.  

there should be a `error occurred` type of status that only happens on the handle of an exception in the build process. something should save to the database that this build is borked

**Comment by tjtelan** [comment]
In prod, this should never happen. But if it does, we need some kind of system error state to report back to the user.

An on brand term we can use: https://www.urbandictionary.com/define.php?term=Rapid%20Unscheduled%20Disassembly
