### ISSUE TITLE
clean up vcs type string conversion in flags

### ISSUE THREAD

**Issue by shankj3** [level11consulting/orbitalci#137]
```golang
oh.VcsType, err = protobuf.VcsTypeStringToSubCredType(oh.VcsTypeStr)
```

^^^ this is v. messy. we should consider instead adding methods to CredType && SubCredType to be able to parse strings etc, and that could be used all over the place in the client to clean up some similar conversion code

ref: #130  -- [comment](https://github.com/shankj3/ocelot/pull/130/files/593821c9f0d217b4448b28253930983c2058c339#r234816360)

**Comment by tjtelan** [comment]
This pattern will go away with the API redesign.
