### ISSUE TITLE
go.sum is recommended to be checked in with code, we don't have a good story around doing that

### ISSUE THREAD

**Issue by eccramer** [level11consulting/orbitalci#179]
Looking at the golang documentation on go.sum, it asserts we should be keeping go.sum checked in alongside ocelot's code.

https://github.com/golang/go/wiki/Modules#should-i-commit-my-gosum-file-as-well-as-my-gomod-file

They suggest you should run `go mod tidy` before commits to make sure that the go.sum file is up-to-date at checkin.

This causes problems for our workflow, as it revolves around vagrant, and it's not immediately clear how we exfiltrate the go.sum file from the vagrant box before checkin.

This might be solvable with synced folders, it's likely just something we need to add to our process.

**Comment by tjtelan** [comment]
Not portable to another hypervisor, but since we're both using virtualbox, I've been using this solution:

https://stackoverflow.com/questions/34448717/how-to-enable-two-way-folder-sync-in-vagrant-with-virtualbox
