### ISSUE TITLE
Names of types in creds.proto are wildly inconsistent

### ISSUE THREAD

**Issue by eccramer** [level11consulting/orbitalci#181]
creds.proto needs a makeover.

The containers that hold VCS, Repo, Apple, and Kubernetes credentials are helpfully named
- `VCSCredsWrapper`
- `RepoCredsWrapper`
- `AppleCredsWrapper`
- `K8SCredsWrapper`

but the containers that hold SSH keys and Notification credentials are called
- `SSHWrap`
- `NotifyWrap`

Internal fields are all over the place too. The field inside of VCSCredWrapper is called `vcs`, but in AppleCredsWrapper it's called `appleCreds`, in K8SCredsWrapper it's called `K8SCreds` and in NotifyWrap it's just called `creds`.

This makes it very difficult to refactor and add features using existing credential types. We need to fix these such that they're consistent on both naming and case.

**Comment by tjtelan** [comment]
Notes from meeting:

* `AllCredsWrapper` doesn't fit the pattern set by other wrapper types. (It is more like the non-existent `VCSCredsWrapper`. It isn't obvious where else `RepoWrapper` is used)
* `NotifyCredsWrap` is named inconsistently
* `SSHWrap` is named inconsistently
* `SSHKeyWrapper` should contain references to an SSH key cipher type
* `GenericCredsWrapper` has comments that don't agree with how it is used (it has ENV and HELM_REPO subtypes)
