### ISSUE TITLE
tracking on who/what triggered a build

### ISSUE THREAD

**Issue by shankj3** [level11consulting/orbitalci#26]
there should be a new column or two added to `build_summary`; *who* triggered the build, then *what* triggered it 
for the who, probably do the username? or maybe just the email associated with the account that commited it

for the what, it should be an enum: 
- CLI
- PR
- PUSH
- POLL

That way we can act on the trigger appropriately, e.g. for PR handling if a build fails

**Comment by tjtelan** [comment]
We have no concept of a user/profile to associate with the event we'd be keeping track of. We can revisit this idea in the future if we ever add in users.
