### ISSUE TITLE
change summary retrieval to be by datetime instead of build id desc

### ISSUE THREAD

**Issue by shankj3** [level11consulting/orbitalci#59]
right now, the summaries are ordered by the `id`, since it is sequential 

i would prefer to create a new column in the `build_summary` table, `create_time` or something that would reflect just exactly when the row was created for the first time, auto generated by the database so we don't have to worry about it (fyi for postgres solution would be like [this](https://stackoverflow.com/questions/9556474/how-do-i-automatically-update-a-timestamp-in-postgresql))

then the ordering can be by the `create_time` instead of `id`. just seems more resilient.

**Comment by tjtelan** [comment]
Strongly disagree. Builds should be sorted by id, not by date. The build id and dates should be temporally related anyway. If this relationship isn't true then something bad is going on.
